# Generated by Django 4.1 on 2022-08-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodeltranslation',
            name='title',
        ),
    ]
