# Generated by Django 4.1 on 2022-08-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0002_remove_mymodeltranslation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodeltranslation',
            name='content',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='mymodeltranslation',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
