# Generated by Django 4.1 on 2022-08-28 07:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0003_mymodeltranslation_content_mymodeltranslation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodeltranslation',
            name='editor',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
